CREATE TABLE `pipeline_parameter` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL COMMENT '参数名，全局唯一，对应argo yaml中参数的name字段，例如：app-name、env等等',
  `label` varchar(100) NOT NULL COMMENT '参数中文名称，前端表单展示的时候用，用于表单的label值',
  `description` varchar(500) DEFAULT NULL COMMENT '参数详细描述，可以用于前端表单tooltip展示',
  `component_type` varchar(50) DEFAULT NULL COMMENT '前端组件类型，参数的展示方式，比如：input、select、radio等等',
  `param_type` varchar(50) NOT NULL COMMENT '参数类型：system-系统参数（用户不可见，系统自动填充）、user-用户参数（用户可见，需填写/选择）',
  `required` tinyint(1) NOT NULL DEFAULT '0' COMMENT '参数是否必填',
  `default_value` varchar(200) DEFAULT NULL COMMENT '参数的默认值，如果其它所有的数据源都获取不到默认值，则使用该默认值',
  `need_system_process` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否需要系统内部处理，用户/外部传入的参数值需要经过系统额外处理（如值映射转换）',
  `regex_pattern` varchar(100) DEFAULT NULL COMMENT '参数需要满足的正则表达式，定义了对参数的校验规则',
  `depend_params` varchar(500) DEFAULT NULL COMMENT '依赖的参数，JSON数组格式，如 ["build-jdk-version"]；被依赖的参数需先求值',
  `refresh_on_changed` tinyint(1) NOT NULL DEFAULT '0' COMMENT '参数值变动后是否刷新整体的参数，一般是参数被其它参数依赖的时候',
  `param_group` varchar(50) NOT NULL COMMENT '参数所属的组别，用于分类展示参数',
  `param_group_sort` int NOT NULL DEFAULT '0' COMMENT '参数在所属组别里面的排序值，定义了展示顺序',
  `option_config` text COMMENT '参数选项配置，JSON数组格式，用于下拉选择、单选按钮等场景',
  `default_value_strategy_config` text COMMENT '默认值计算策略配置，JSON数组格式，定义默认值的来源和优先级',
  `creator` varchar(45) NOT NULL COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_param_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utfmb3 COMMENT='流水线参数定义表，全局共享，规范化argo workflow template的参数管理';
